vich_uploader:
    db_driver: orm

    mappings:
        musicproject_image:
            uri_prefix:         /uploads/images/musicProjects
            upload_destination: "%kernel.root_dir%/../web/uploads/images/musicProjects"
            namer:              vich_uploader.namer_uniqid
            delete_on_update:   true
            delete_on_remove:   true