fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: app_musicproject_index
        permanent: true

admin_dashboard:
    path: /admin
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: avanzu_admin_home
        permanent: true
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix: /


admin:
    resource: "@AppBundle/Controller/Admin"
    prefix: /admin
    type:     annotation



