# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    app.admin.menu_listener.class: AppBundle\EventListener\AdminSidebarMenuListener

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    my_admin_bundle.menu_listener:
        class: '%app.admin.menu_listener.class%'
        tags:
            - { name: kernel.event_listener, event:theme.sidebar_setup_menu, method:onSetupMenu }
    my_admin_bundle.breadcrumb_listener:
        class: '%app.admin.menu_listener.class%'
        tags:
            - { name: kernel.event_listener, event:theme.breadcrumb, method:onSetupMenu }